### PR TITLE
Splash page with Aurora Effect

### PR DESCRIPTION
**Pull request by jhueyy**
Added Aurora effect and button to splash page. Might implement lamp under title. Sparkles was a bit too much and caused unnecessary lag. Aurora is also laggy at times.

### CODE REVIEW

**Comment by JLpro-cd** [comment]
Thank you! Appreciate you looking out for performance.

**Review by nonetypes — DISMISSED** [review]
Looks good to me. Nice job!

**Comment by enriqueboi** [comment]
Looks good

**Review by Castro19 — APPROVED** [review]
Changes look great, thank you!

**Comment by enriqueboi** [comment]
Nice add, and looking out for performance

**Pull request merged**
