### PR TITLE
Completed web scraping functionality for retrieving articulation agreements from assit.org

### PR DESCRIPTION
**Pull request by nonetypes**
### Overview
This pull request includes the complete implementation of the `webScraper.py` script, designed to scrape, process, serialize, and save articulation agreement data between Cal Poly and every California community college. The data is stored as individual JSON files.

### Usage Instructions
To run `webScraper.py`, ensure the following setup:

1. **Browser Installation**:
   - Firefox or Chrome must be installed.
   - By default, a headless browser instance uses Firefox.
   - Set the global `CHROME` variable at the top of `webScraper.py` to `True` to use Chrome instead.

2. **Python Environment**:
   - Python 3.x is required.

3. **Required Libraries**:
   - Install the necessary Python libraries using pip:
     ```
     pip install selenium beautifulsoup4 requests
     ```
   - **Selenium** for web browser automation.
   - **BeautifulSoup4** for parsing HTML and XML documents.
   - **Requests** for making HTTP requests in Python.

Ensure all dependencies are installed as described above to avoid any runtime errors.

### Implementation Details
- **Script**: `webScraper.py`
  - **Functionality**: Scrapes, processes, serializes, and saves data.
  - **Output**: Articulation agreements are saved in `server/json_data/articulationAgreements` as `.JSON` files.

### Dependencies
- **groupCourses.py**
  - This module translates flat arrays of courses and corresponding conjunctions into multidimensional arrays. It retains relational information across groups of courses and within subgroups.
- **util.py**
  - Contains miscellaneous helper functions used in `webScraper.py`.

### Additional changes in this pull request
- Added Python caching files and directories to `.gitignore` to prevent unnecessary tracking of files.

### Future Work
Additional data verification of articulation agreements should be conducted to ensure proper groupings of courses are being outputted to the .JSON files. If discrepancies are found between these files and assist.org, groupCourses.py will need to be debugged.

### CODE REVIEW

**Review by Castro19 — APPROVED** [review]
Changes look good, thank you!

**Comment by JLpro-cd** [comment]
LGTM!

**Comment by enriqueboi** [comment]
Looks great

**Review by jhueyy — COMMENTED** [review]
Great work!

**Comment by AGunnarP** [comment]
Neat

**Pull request merged**
