### PR TITLE
Testing implemented using Cypress

### PR DESCRIPTION
**Pull request by Castro19**
Testing for homepage options transferring to schedule page title is tested and functional.

### CODE REVIEW

**Comment by JLpro-cd** [comment]
Looks Great!

**Comment by enriqueboi** [comment]
Good job testing

**Comment by jhueyy** [comment]
Great job using Cypress to test!

**Review by jhueyy — APPROVED** [review]

**Review by JLpro-cd — APPROVED** [review]

**Comment by nonetypes** [comment]
Nice job! Thank you!

**Pull request merged**
